package javafromkotlin.exception

fun main() {
    val ex = WithException()
    ex.throwsException()
}